// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'convert-done'
  | 'convert-error'
  | 'convert-no-backend'
  | 'convert-no-pdf'
  | 'convert-no-selection'
  | 'convert-progress'
  | 'convert-test-ok'
  | 'menu-convert'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-finish';
