// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'convert-test-ok'
  | 'menu-convert'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-finish';
